### PR TITLE
Allow client reconnection

### PR DESCRIPTION
**Pull request by endel**
(Implements #147)

I've set a poll to gather what you guys think about this feature being enabled by default or not. What do you think?

[](https://api.gh-polls.com/poll/01CDFXAWAZTHJB7223G5NVM4CN/enabled%20by%20default/vote)
[](https://api.gh-polls.com/poll/01CDFXAWAZTHJB7223G5NVM4CN/disabled%20by%20default/vote)

Things to consider when reconnection is enabled:
- The rooms will live for a bit longer (15 seconds by default), even if there're no more clients connected to it and `autoDispose` is set to `true`.
- Reconnecting clients will skip `requestJoin` method, since it was authorized already before.

**Usage**

```typescript
class MyRoom extends Room {
  onJoin (client) {
    this.state.setupClient(client.sessionId);
  }

  async onLeave (client) {
    this.state.inactivateClient(client.sessionId);

    try {
      // allow client to reconnect within 20 seconds
      const reconnectedClient = await this.allowReconnection(client, 20); 

      // client reconnected!
      this.state.reactivateClient(client.sessionId);

    } catch (e) {
      // client couldn't reconnect within 20 seconds
      this.state.removeClient(client.sessionId);
    }
  }
}
```

### CODE REVIEW

**Comment by sandrosc** [comment]
Will we be able to change allowReconnection dynamically?

**Comment by endel** [comment]
Hey @sandrosc, yes, it's possible to enable and disable `allowReconnection` at any time.

**Comment by sandrosc** [comment]
@endel awesome!

**Comment by endel** [comment]
It turns out I've overlooked this feature, and the implementation will need to be slightly different. I've updated the usage example in the description of this pull-request.

You may call `allowReconnection()` per client, and it will return a promise, that is resolved whenever the user has reconnected. The promise is rejected after the timeout specified. (15 seconds by default)

This way you have full control of the events, and you can flag users as inactive accordingly.

**Comment by Wenish** [comment]
if i would upgrade to the version. do i need to change something so that everything works the same?

**Comment by endel** [comment]
@Wenish `onAuth` will continue to be called before joining. I think `requestJoin` won't be necessary since this method is used to determine which room the client will join, and we already know exactly which room the client should connect to. 

If you're using version `0.9.x` there's nothing else to update! `allowReconnection` is totally optional.

**Pull request merged**
