### PR TITLE
only send data when client is OPEN

### PR DESCRIPTION
**Pull request by seiyria**
not sure specifically if this is how you'd want this implemented, but let me know and I can update it.

#171

### CODE REVIEW

**Comment by oyed** [comment]
I think this should be enough, however it doesn't stop the calls made being sent in the first place - probably something to look in to via a separate PR/issue.

**Comment by seiyria** [comment]
That's true. This will prevent the errors from spreading but debugging why they happen was tougher since I can only ever reproduce these things on prod, but my build process doesn't let me adequately test colyseus changes on prod.

**Comment by endel** [comment]
Thanks a lot @seiyria, there was some checks for `OPEN` connections in some places, and now I've centralized it in the `send` method, which is used everywhere. (https://github.com/gamestdio/colyseus/commit/5c37e1bed34b55769c95e4ce5d1a6918306e5000)

**Comment by seiyria** [comment]
Great. That works for me, thanks!

**Pull request closed without merging**
