### PR TITLE
update issue template

### PR DESCRIPTION
**Pull request by Wenish**
it help to create a new issue.
and the issue gets more context than just some phrases..

### CODE REVIEW

**Comment by endel** [comment]
Hey @Wenish, sorry the delay to reply here.

I believe requiring `Expected Behavior`, `Current Behavior` and `Possible Solution` might be too much, since most users of Colyseus have little to no knowledge of Node.js or networking. I like having `Context` and `Your Environment`, though. 

Can you make this change? Cheers!

**Comment by Wenish** [comment]
@endel np ;)

i took the 3 things out and added some more example lines in the "your environment" section.

**Comment by seiyria** [comment]
Can you change "issue track" to "issue tracker"? Additionally, I think you should remove unity version from this template - if desired, it could be added to the unity plugin template.

**Comment by oyed** [comment]
@seiyria Agreed - Client-based frameworks should be restricted to their own repos issues, not `colyseus`

**Comment by Wenish** [comment]
@seiyria i removed the line with unity and browser version

**Comment by Wenish** [comment]
@endel what do u think?

**Comment by endel** [comment]
Thanks @Wenish, it's looking good! 🤗

**Pull request merged**
